/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ExecutionStatusBadge: typeof import('./components/task/ExecutionStatusBadge.vue')['default']
    PriorityBadge: typeof import('./components/task/PriorityBadge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/layout/Sidebar.vue')['default']
    StatusActions: typeof import('./components/task/StatusActions.vue')['default']
    StatusBadge: typeof import('./components/task/StatusBadge.vue')['default']
    SystemSettingsDialog: typeof import('./components/settings/SystemSettingsDialog.vue')['default']
    TaskForm: typeof import('./components/task/TaskForm.vue')['default']
    TaskLinkList: typeof import('./components/task/TaskLinkList.vue')['default']
    TaskListForm: typeof import('./components/task-list/TaskListForm.vue')['default']
    TAvatar: typeof import('tdesign-vue-next/esm')['Avatar']
    TButton: typeof import('tdesign-vue-next/esm')['Button']
    TCard: typeof import('tdesign-vue-next/esm')['Card']
    TDatePicker: typeof import('tdesign-vue-next/esm')['DatePicker']
    TDialog: typeof import('tdesign-vue-next/esm')['Dialog']
    TDropdown: typeof import('tdesign-vue-next/esm')['Dropdown']
    TDropdownItem: typeof import('tdesign-vue-next/esm')['DropdownItem']
    TDropdownMenu: typeof import('tdesign-vue-next/esm')['DropdownMenu']
    TForm: typeof import('tdesign-vue-next/esm')['Form']
    TFormItem: typeof import('tdesign-vue-next/esm')['FormItem']
    TIcon: typeof import('tdesign-vue-next/esm')['Icon']
    TInput: typeof import('tdesign-vue-next/esm')['Input']
    TInputNumber: typeof import('tdesign-vue-next/esm')['InputNumber']
    TLink: typeof import('tdesign-vue-next/esm')['Link']
    TLoading: typeof import('tdesign-vue-next/esm')['Loading']
    TRadio: typeof import('tdesign-vue-next/esm')['Radio']
    TRadioGroup: typeof import('tdesign-vue-next/esm')['RadioGroup']
    TSelect: typeof import('tdesign-vue-next/esm')['Select']
    TSpace: typeof import('tdesign-vue-next/esm')['Space']
    TTable: typeof import('tdesign-vue-next/esm')['Table']
    TTag: typeof import('tdesign-vue-next/esm')['Tag']
    TTextarea: typeof import('tdesign-vue-next/esm')['Textarea']
    TTooltip: typeof import('tdesign-vue-next/esm')['Tooltip']
  }
}
